export default Object.freeze({
  ADMIN: Object.freeze({
    OFFICE_USER: 'office_user',
    OFFICE_USER_ROLE: 'office_user_role',
    SYSTEM_CONFIG: 'system_config',
    TENANT_CONFIG: 'tenant_config',
    ROLE: 'role',
    BRANCH: 'branch',
    PERMISSION: 'permissions',
    ROLE_PERMISSION: 'role_permissions',
    PAGE: 'pages',
    BLOG: 'blogs',
    CATEGORY: 'categories',
    PRODUCT: 'products',
    USER: 'users',
    FEEDBACK: 'feedback',
    ORDER: 'orders',
    ORDER_ITEM: 'order_items',
    ORDER_STATUS: 'order_statuses',
  }),
  APP: Object.freeze({}),
});
